document.write('<meta http-equiv="Content-Type" content="text/html;charset="utf-8" />');
document.write('<meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />');
document.write('<link rel="shortcut icon" href="/img/fav.png" />');
document.write('<title>来客iPOS</title>');
document.write('<meta name="description" content="来客iPOS介绍"/>');
document.write('<meta name="author" content="Like" />');
document.write('<meta property="og:title" content=""/>');
document.write('<meta property="og:description" content="Like, ipos, iPOS家族, 来客, 上海理客信息技术有限公司, 上海来客之家网络有限公司"/>');
document.write('<meta property="og:site_name" content="来客iPOS"/>');
document.write('<meta property="og:type" content="website"/>');
document.write('<meta property="og:url" content="http://www.likeit.cn/index.html"/>');
document.write('<link href="/css/bootstrap.min.css" rel="stylesheet" type="text/css" />');
document.write('<link href="/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>');
document.write('<link href="/css/superfish.css" rel="stylesheet" type="text/css"/>');
document.write('<link href="/css/jquery.dlmenu.css" rel="stylesheet" type="text/css"/>');
document.write('<link rel="stylesheet" href="/css/magnific-popup.css" type="text/css"/>');
document.write('<link rel="stylesheet" href="/css/layerslider.css" type="text/css"/>');
document.write('<!--[if IE 7]>');
document.write('<link type="text/css" rel="stylesheet" href="/css/font-awesome-ie7.min.css">');
document.write('<![endif]-->');
document.write('<link href="/css/custom.css" rel="stylesheet" type="text/css"/>');
document.write('<link href="/css/responsive.css" rel="stylesheet" type="text/css"/>');
document.write('<!--[if lte IE 9]>');
document.write('<link rel="stylesheet" href="/css/lte-ie9.css" type="text/css">');
document.write('<![endif]-->');
document.write('<link rel="stylesheet" href="/css/like.css" type="text/css">');
document.write('<style id="colorChanges" type="text/css"></style>');
document.write('<script src="js/jquery.js"></script>');
document.write('<script src="js/modernizr.js"></script>');
document.write('<script src="js/like/like_common.js"></script>');